# user input
print("Please enter your name: ", end="")
name = input()
print("Please enter your TP number: ", end="")
tp_number = input()
print("Please enter your marks: ", end="")
marks = input()
print("Please enter your grade: ", end="")
grade = input()
print("Please enter your CGPA: ", end="")
cgpa = input()

# output
print("Your details are as follows:")
print("Name:", name)
print("TP number:", tp_number)
print("Marks:", marks)
print("Grade:", grade)
print("CGPA:", cgpa)
print("Thank you for registering")
